name: CI Tests
on:
  workflow_dispatch: 
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        uses: actions/checkout@v3
      
      - name: Step 2
        uses: actions/setup-java@v18
        with:
          java-version: 18
        
      - name: Step 3
        run: mvn -B package --file pom.xml
   
